feat(nimbus): default to archive, enable era files download (#473)

diff --git a/charts/nimbus/templates/nimbus/statefulset.yaml b/charts/nimbus/templates/nimbus/statefulset.yaml
--- a/charts/nimbus/templates/nimbus/statefulset.yaml
+++ b/charts/nimbus/templates/nimbus/statefulset.yaml
@@ -142,6 +142,43 @@ spec:
               mountPath: "/storage"
       {{- end }}
       {{- if $values.trustedNodeSync.enabled }}
+      {{- if $values.trustedNodeSync.eraFiles }}
+        - name: init-era-files
+          image: "{{ $values.trustedNodeSync.initContainer.image.repository }}:{{ $values.trustedNodeSync.initContainer.image.tag }}"
+          imagePullPolicy: {{ .Values.image.pullPolicy }}
+          securityContext:
+            readOnlyRootFilesystem: true
+            capabilities:
+              drop:
+                - ALL
+          env:
+            - name: ERA_FILES_URL
+              value: {{ $values.trustedNodeSync.eraFilesUrl }}
+          command:
+            - sh
+            - -ac
+            - |
+              set -x;
+              ERA_FILES_STATE_FILE=/storage/era/.init-era-files
+              TRUSTED_NODE_SYNC_STATE_FILE=/storage/.init-trusted-node-sync
+              if [ -f "$TRUSTED_NODE_SYNC_STATE_FILE" ]; then
+                echo "Trusted Node Sync already ran. Skipping..."
+              elif [ ! -f "$ERA_FILES_STATE_FILE" ]; then
+                mkdir -p /storage/era
+                cd /storage/era
+                wget --no-parent  -A '*.era' -q --show-progress -nd -r -c "$ERA_FILES_URL"
+                [ "$?" != "0" ] && echo "Download failed" && exit 1
+                echo $ERA_FILES_URL > $ERA_FILES_STATE_FILE
+              else
+                cat $ERA_FILES_STATE_FILE
+                echo "Era files already downloaded. Skipping..."
+              fi
+          volumeMounts:
+            - name: storage
+              mountPath: /storage
+            - name: tmp
+              mountPath: /tmp
+      {{- end }}
         - name: init-trusted-node-sync
           image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
           imagePullPolicy: {{ .Values.image.pullPolicy }}
@@ -161,12 +198,18 @@ spec:
                 /home/user/nimbus-eth2/build/nimbus_beacon_node \
                   trustedNodeSync \
                   --data-dir=/storage \
+                {{- if $values.trustedNodeSync.eraFiles }}
+                  --reindex=true \
+                {{- end }}
                 {{- range $arg := $values.trustedNodeSync.extraArgs }}
                   {{- $arg | nindent 18 }} \
                 {{- end }}
                   --trusted-node-url=$TRUSTED_NODE_URL
-                echo $?
-                echo $TRUSTED_NODE_URL > $TRUSTED_NODE_SYNC_STATE_FILE
+                if [ $? -eq 0 ]; then
+                  echo $TRUSTED_NODE_URL > $TRUSTED_NODE_SYNC_STATE_FILE
+                else
+                  exit 1
+                fi
               else
                 cat $TRUSTED_NODE_SYNC_STATE_FILE
                 echo "Trusted node sync already run. Skipping..."
@@ -207,6 +250,7 @@ spec:
               set -ex;
               exec /home/user/nimbus-eth2/build/nimbus_beacon_node \
                 --data-dir=/storage \
+                --history={{ $values.history }} \
               {{- if $values.executionClientUrl }}
                 --web3-url={{ $values.executionClientUrl }} \
               {{- end }}
